.travis.yml, README.md, build.sbt, docs/project/plugins.sbt
Since Playframework 2.4.0 will support only Java 8, this project needs to be compiled with Java 8 too.
=> Configure build to use Java 8

sbt-play-ebean/src/main/scala/play/ebean/sbt/SbtEbean.scala
Currently only .java models are updated with SBT when they are enhanced by ebeans causing recompilation of all scala models that have been enhanced even if no other changes are made. This will ensure that all tracked products get updated.
=> Ensure that all sbt tracked products are updated if enhanced

docs/manual/working/javaGuide/main/sql/JavaEbean.md
The avaje.org website is outdated and is already linking to Github project at some places.
=> Update documentation links

build.sbt, play-ebean/src/main/java/play/db/ebean/DefaultEbeanConfig.java, play-ebean/src/main/java/play/db/ebean/EbeanParsedConfig.java, play-ebean/src/main/java/play/db/ebean/ModelsConfigLoader.java, play-ebean/src/test/java/play/db/ebean/EbeanParsedConfigTest.java, sbt-play-ebean/src/main/scala/play/ebean/sbt/SbtEbean.scala, sbt-play-ebean/src/sbt-test/sbt-ebean/enhancement/conf/application.conf
Fixes #18 - the sbt config loading wasn't updated to support lists
The way that the sbt plugin used to discover the models to enhance used to be roughly copied config loading mechanism from Play, followed by roughly copying the config lookup mechanism.  This unifies them, so it now uses *the* config loading mechanism from Play, and *the* play-ebean config lookup code.
=> Unify the config loading between sbt and runtime

build.sbt
Play master has dropped the dependency on play-enhancer, so the Play ebean sbt plugin needs an explicit depenency on it now.
Fixes the nightly build.
=> Add dependency on play-enhancer

.travis.yml
* Only cache the ivy cache, not the local repo
* Remove ebean artifacts from the cache before caching
At the moment, the build actually takes a long time at the end to repackage the cache, this should fix that.
=> Improved caching

build.sbt
The version should be changed again once Play 2.4.0-RC3 is out.
=> Bumped Play version to minimum version required to compile

build.sbt, docs/manual/working/javaGuide/main/sql/code/javaguide/ebean/Task.java
Ebean has released version 4.8.1 (see https://github.com/ebean-orm/avaje-ebeanorm/releases).  This release fixes an accidental API change that prevents listeners from being unloaded.
=> Update plugin to use new version of ebean ORM

build.sbt, play-ebean/src/main/java/play/db/ebean/EbeanDynamicEvolutions.java, sbt-play-ebean/src/main/scala/play/ebean/sbt/PlayEbean.scala
Upgrade for Ebean 6.7.1.  This resolves issue #53
=> Upgrade for Ebean 6.7.1

.travis.yml, build.sbt, docs/build.sbt, docs/project/plugins.sbt, play-ebean/src/main/java/play/db/ebean/TransactionalAction.java, project/plugins.sbt, sbt-play-ebean/src/sbt-test/sbt-ebean/enhancement/build.sbt, sbt-play-ebean/src/sbt-test/sbt-ebean/model-loading/build.sbt
Because `Action.call` does no longer declare to throw in its signature, there is
no need to wrap `Throwable` into a runtime exception.
This commit is related to https://github.com/playframework/playframework/commit/f9e2d1917019f2bb1b2876b464014640965bade1#diff-02a5773c77e32371d3322bbb15c320d7L27 (see playframework/playframework@f9e2d1917019f2bb1b2876b464014640965bade1)
=> Project compiles against Play master. Fix #49

build.sbt
This commit will be rolled back as soon as play-ebean 3.0.0-M1 for Play 2.5.0-M1
is released.
=> Disabling cross building to be able to release play-ebean against Play 2.5.0-M1

docs/manual/working/javaGuide/main/sql/code/ebean.sbt
The docs use 3.1.1 still, see https://www.playframework.com/documentation/2.6.x/JavaEbean for reference
=> Update the docs to use 4.0.0-SNAPSHOT

docs/project/build.properties, play-ebean/src/main/java/play/db/ebean/DefaultEbeanConfig.java, play-ebean/src/main/java/play/db/ebean/EbeanConfig.java, play-ebean/src/main/java/play/db/ebean/EbeanDynamicEvolutions.java, play-ebean/src/main/java/play/db/ebean/EbeanModule.java, play-ebean/src/main/java/play/db/ebean/EbeanParsedConfig.java, play-ebean/src/main/java/play/db/ebean/ModelsConfigLoader.java, play-ebean/src/main/java/play/db/ebean/Transactional.java, play-ebean/src/main/java/play/db/ebean/TransactionalAction.java, play-ebean/src/main/java/play/db/ebean/package-info.java, play-ebean/src/test/java/play/db/ebean/EbeanParsedConfigTest.java, project/build.properties, sbt-play-ebean/src/main/scala/play/ebean/sbt/PlayEbean.scala
Copyright was Typesafe in the headers, changed to Lightbend.
=> Update copyright to lightbend

build.sbt, play-ebean/src/main/java/play/db/ebean/DefaultEbeanConfig.java
*ebean 10.3.1->10.4.1
*playEnhancer 1.1.0->1.2.1
removed setH2ProductionMode() method invocation, as soon as it is not provided by ServerConfig class anymore
=> dependencies update:

play-ebean/src/main/java/play/db/ebean/DefaultEbeanConfig.java
In ServerConfig class, default value of the attribute defaultServer is true. So we have to change it to false when ebeanConfig.getDefaultDatasource() is not equals to the config key
=> Fix Default server status

docs/manual/working/javaGuide/main/sql/code/ebean.sbt
I updated the version in documentation. The main reason is that version 4.0.1 is not available for `Scala 2.12` and `Sbt 1.x`.
This is an issue for new users that starts from `playframework/play-java-seed.g8` that follows the documentation.
=> Update plugin version in documentation

build.sbt, docs/build.sbt, docs/project/plugins.sbt, play-ebean/src/main/java/play/db/ebean/DefaultEbeanConfig.java, play-ebean/src/main/java/play/db/ebean/EbeanParsedConfig.java, play-ebean/src/main/java/play/db/ebean/ModelsConfigLoader.java, project/plugins.sbt, sbt-play-ebean/src/sbt-test/sbt-ebean/enhancement/build.sbt, sbt-play-ebean/src/sbt-test/sbt-ebean/model-loading/build.sbt
Also updates to the latest version of Ebean.
I've copied `play.libs.Classpath` helper class, which was removed in Play 2.7, to here. It was not used in Play itself anymore, but it is useful for Play Ebean.
=> Update to Play 2.7.0-M1

.travis.yml, README.md, build.sbt, play-ebean/src/test/java/play/db/ebean/EBeanComponentsTest.java, sbt-play-ebean/src/main/scala-sbt-0.13/play/ebean/sbt/PlayEbean.scala, sbt-play-ebean/src/main/scala-sbt-1.0/sbt/PlayEbean.scala, version.sbt
- Upgrade to play 2.8.0
- Upgrade to ebean 11.45.1
- Included jaxb as a transitive dependency, since ebean requires it and if not included then this plugin will not work out of the box with Java 11
=> feat: upgrade to play 2.8.1 & ebean 11.45.1

project/plugins.sbt
Looks like the master Travis Build is failing because it wants the MiMa plugin. Adding it here.
=> Adding MiMa plugin for travis build

play-ebean/src/main/java/play/db/ebean/ModelsConfigLoader.java
The goal of this PR is to modify the way Configuration was moved to Config in order to keep the capability to build sub projects with PlayEbean inside.
See https://github.com/playframework/play-ebean/issues/209 for more details.
=> Fix PlayEbean configuration loading for sub projects (#209)

.travis.yml, build.sbt
Fixes #216, #221 reference to PR #217
It will help to evolve #208 and get things on track!
=> Fixes publish release to Sonatype repository.

build.sbt, docs/project/build.properties, project/build.properties, sbt-play-ebean/src/main/scala-sbt-1.0/play/ebean/sbt/PlayEbean.scala
sbt 1.4.x introduces a breaking changes to how plugins can hook
into the compiler as well as some API changes for stamping files
so that the incremental compiler can recognize modifications
This pull requests updates sbt-play-ebean to account for those
changes with respect to ebean enhancement.
=> Fixes #208 - Support sbt 1.4.x+

.github/workflows/release-drafter.yml, .travis.yml, README.md, RELEASING.md
@SethTisue and @ihostage already renamed the `master` branch in some play repos:
* https://github.com/playframework/cachecontrol/pull/163
* https://github.com/playframework/play-file-watch/pull/136
* https://github.com/playframework/play-json/pull/598
* https://github.com/playframework/play-soap/pull/282
* https://github.com/playframework/play-ws/pull/597
* https://github.com/playframework/twirl/pull/416
Now that we are centralising configs in the [`.github`](https://github.com/playframework/.github) repo it's a good idea that all repos have the same default branch name.
To change to `main` locally (if the remote to this repo is called `upstream`):
```sh
git branch -m master main # rename master to main (actually "move")
git fetch upstream
git branch -u upstream/main main # set upstream …
```
=> Rename master branch to main

.scalafmt.conf, sbt-play-ebean/src/main/scala-sbt-1.0/play/ebean/sbt/PlayEbean.scala
After update Scalafmt to 3.5.2 it has broken config
I fixed that and successfully run `scalafmtCheck`
Without this error appeared:
```
sbt:play-ebean-root> scalafmtAll
[error] stack trace is suppressed; run 'last core / Test / scalafmt' for the full output
[error] stack trace is suppressed; run 'last core / Compile / scalafmt' for the full output
[error] stack trace is suppressed; run 'last plugin / Compile / scalafmt' for the full output
[error] (core / Test / scalafmt) org.scalafmt.sbt.ScalafmtSbtReporter$ScalafmtSbtError: scalafmt: Invalid config: 3 errors
[error] [E0] D:\Documents\GitHub\play-ebean\.scalafmt.conf:4:0 error: Type mismatch;
[error]   found    : String (value: "JavaDoc")
[error]   expected : Object
[error] docstrings = JavaDoc
[error] ^
[error]
[error] [E1] Presets$: …
```
=> Fix Scalafmt config

docs/build.sbt, play-ebean/src/main/java/play/db/ebean/DefaultEbeanConfig.java, sbt-play-ebean/src/main/scala-sbt-1.0/play/ebean/sbt/PlayEbean.scala, sbt-play-ebean/src/sbt-test/sbt-ebean/enhancement/build.sbt, sbt-play-ebean/src/sbt-test/sbt-ebean/enhancement/tests/models/TestTask.java, sbt-play-ebean/src/sbt-test/sbt-ebean/model-loading/build.sbt
Fixes #301
Tested both in dev and prod mode by `publishLocal` snapshot and `docker:publishLocal` in Docker container (the same as production environment in Jelastic)
There was a crash before the fix, now all models are registered correctly, checked all CRUD operations and all models
I don't know how to provide such tests, you can check yourself @mkurz
Let's see changes in https://github.com/playframework/play-ebean/commit/692ae03c00485d1098ef570dffe69c73ba273f22 here:
https://github.com/playframework/play-ebean/blob/692ae03c00485d1098ef570dffe69c73ba273f22/play-ebean/src/main/java/play/db/ebean/DefaultEbeanConfig.java#L235
According Javadoc in `FilterBuilder.includePackage`, you can see implementation - `FilterBuilder.prefixPattern`, which does all work for you, so you should not change …
=> Fix PersistenceException in production

docs/manual/working/javaGuide/main/sql/code/javaguide/ebean/Task.java, project/Dependencies.scala, sbt-play-ebean/src/sbt-test/sbt-ebean/enhancement/app/models/Task.java
Let's see. IMHO makes sense since basically everyone is switching over recently. Planning to do the same with Play-Java-JPA:
* https://github.com/playframework/playframework/pull/11079
Switches from `javax.persistence` to `jakarta.persistence`.
See 
* https://github.com/ebean-orm/ebean/issues/2835#issuecomment-1449343867
> As release `13.14.0` onwards we will additionally release a Jakarta version, so we have released `13-14.0-jakarta` version of the various ebean modules.
* https://github.com/ebean-orm/ebean/issues/2920
* https://github.com/ebean-orm/ebean/discussions/2839
* https://repo1.maven.org/maven2/io/ebean/ebean/
=> Switch to Jakarta persistence

build.sbt, play-ebean/src/main/java/play/db/ebean/EBeanComponents.java, play-ebean/src/main/java/play/db/ebean/EbeanDynamicEvolutions.java
Now that https://github.com/playframework/playframework/pull/11917 got merged we should respect that config.
=> Respect `play.evolutions[.db.default].path` config for dynamic evolutions

play-ebean/src/main/java/play/db/ebean/DefaultEbeanConfig.java
This change will prevent issue #402 by skipping the creation and registration of a `DatabaseConfig` for ebean datasources which have no db connection parameters configured.
With this PR, users are able to specify and enhance Ebean models for datasources that may not be available on application startup, or that may be connected at a later stage during runtime. The `ebean.<datasource>` configuration can be specified without the need to also specify `db.<datasource>`.
```hocon
play.evolutions.db.foo.enabled = false
ebean.foo = ["models.foo.*"]
// NOT CONFIGURED
// db.foo { 
// }
```
After a few tests, this seems to behave as I'd expect.
- Trying to query a model that was skipped will lead to the `DataSource user is null?` exception
- Once a connection is establised manually (see below), …
=> Skip connection for datasources with omitted db configuration

project/Dependencies.scala
- Try to fix #437
- Latest version: https://github.com/ebean-orm/ebean/releases/tag/15.0.1
=> Ebean 15.0.1
