playframework/play-ebean

- build.sbt
Issue #7 explains why this is important. Also, it keeps this project updated with Ebean.
> Update ebean and ebean-agent

- build.sbt
- project/plugins.sbt
* sbt plugin snapshots now got to sonatype
* Included bintray release and sonatype release steps in release
> Fixed nightly deploys

- play-ebean/src/main/java/play/db/ebean/EbeanDynamicEvolutions.java
Play ebean currently fails to compile against Play master since the deprecated Files methods were removed.
> Remove reliance on Play Files API

- build.sbt
- sbt-play-ebean/src/sbt-test/sbt-ebean/enhancement/build.sbt
This will keep the plugin consistent with playframework/playframework#4334.
> Bump scala versions to 2.10.5 and 2.11.6

- build.sbt
This is the same version used by play and other projects related to Playframework.
> Upgrade to typesafe config 1.3.0 final

- build.sbt
No binary compatibility issues with the previous release. Release notes for each version:
1. https://github.com/ebean-orm/avaje-ebeanorm/releases/tag/avaje-ebeanorm-4.6.3
2. https://github.com/ebean-orm/avaje-ebeanorm/releases/tag/avaje-ebeanorm-4.7.1
3. https://github.com/ebean-orm/avaje-ebeanorm/releases/tag/avaje-ebeanorm-4.7.2
> Upgrade ebean to version 4.7.2

- build.sbt
Fixes logging issue https://github.com/ebean-orm/avaje-ebeanorm/issues/501
> Upgrade to the latest version of Ebean

- play-ebean/src/main/java/play/db/ebean/DefaultEbeanConfig.java
- play-ebean/src/main/java/play/db/ebean/EbeanConfig.java
- play-ebean/src/main/java/play/db/ebean/EbeanDynamicEvolutions.java
- play-ebean/src/main/java/play/db/ebean/EbeanModule.java
- play-ebean/src/main/java/play/db/ebean/EbeanParsedConfig.java
- play-ebean/src/main/java/play/db/ebean/TransactionalAction.java
Also, extract some methods so we can have smaller/simpler
methods at the code base.
> Refactor to use Java 8 lambdas

- .travis.yml
- README.md
- build.sbt
- project/plugins.sbt
1. https://codecov.io/github/playframework/play-ebean?ref=master
2. https://github.com/sbt/jacoco4sbt and https://github.com/sbt/jacoco4sbt/wiki
3. https://github.com/codecov/example-java
> Enable code coverage using codecov and jacoco4sbt

- build.sbt
- docs/project/plugins.sbt
- play-ebean/src/main/java/play/db/ebean/DefaultEbeanConfig.java
1. Play framework to version 2.5.2
2. Ebean to version 7.6.1
3. Ebean agent to version 4.9.2
> Upgrade dependencies

- .gitignore
- build.sbt
- docs/manual/working/javaGuide/main/sql/code/javaguide/ebean/JavaEbeanTest.java
- docs/manual/working/javaGuide/main/sql/code/javaguide/ebean/Task.java
- sbt-play-ebean/src/sbt-test/sbt-ebean/enhancement/app/models/Task.java
Relative to issue #91, this pull request do the following changes :
- Add IntelliJ project file to .gitignore file
- Upgrade Ebean to prior version 8.2.3
- Upgrade Ebean ORM Agent to prior version 8.1.1
- Upgrade _Task.java_ (Unit tests) to be compliant with Ebean 8.2.3
- Upgrade _JavaEbeanTest.java_ (Unit tests) to be compliant with Ebean 8.2.3
> Feature #91: Upgrade Ebean

- build.sbt
This Pull Request propose to upgrade Ebean to its prior version 8.4.1 (October 2016). This version fix critical issue with iterators: the method _hasNext()_ consume data rather than just check if data are available. More information about this issue at https://github.com/ebean-orm/ebean/issues/821.
> Upgrade Ebean to prior version 8.4.1

- build.sbt
- docs/build.sbt
- docs/manual/working/javaGuide/main/sql/code/ebean.sbt
- docs/project/build.properties
- docs/project/plugins.sbt
- play-ebean/src/main/java/play/db/ebean/EbeanParsedConfig.java
- play-ebean/src/test/java/play/db/ebean/EbeanParsedConfigTest.java
- project/build.properties
- project/plugins.sbt
- sbt-play-ebean/src/main/scala/play/ebean/sbt/PlayEbean.scala
- sbt-play-ebean/src/sbt-test/sbt-ebean/enhancement/build.sbt
- sbt-play-ebean/src/sbt-test/sbt-ebean/model-loading/build.sbt
- version.sbt
1. Upgrade sbt to version 0.13.13
2. Cross building for Scala 2.11 and Scala 2.12
3. Upgrade interplay to version 1.3.4
> Upgrades to Play 2.6.0 M1

- docs/manual/working/javaGuide/main/sql/code/javaguide/ebean/JavaEbeanTest.java
- docs/manual/working/javaGuide/main/sql/code/javaguide/ebean/Task.java
- play-ebean/src/main/java/play/db/ebean/DefaultEbeanConfig.java
- play-ebean/src/main/java/play/db/ebean/EbeanDynamicEvolutions.java
- play-ebean/src/main/java/play/db/ebean/EbeanParsedConfig.java
- sbt-play-ebean/src/sbt-test/sbt-ebean/enhancement/app/models/Task.java
> Just a few fixes

- build.sbt
- play-ebean/src/main/java/play/db/ebean/DefaultEbeanConfig.java
- play-ebean/src/main/java/play/db/ebean/EBeanComponents.java
- play-ebean/src/test/java/play/db/ebean/EBeanComponentsTest.java
Adds ebean components for Java compile time DI.
> Add ebean components

- .gitignore
- build.sbt
- docs/manual/working/javaGuide/main/sql/JavaEbean.md
- docs/manual/working/javaGuide/main/sql/code/javaguide/ebean/JavaEbeanTest.java
- docs/manual/working/javaGuide/main/sql/code/javaguide/ebean/MyServerConfigStartup.java
- docs/manual/working/javaGuide/main/sql/code/javaguide/ebean/Task.java
- docs/project/build.properties
- play-ebean/src/main/java/play/db/ebean/DefaultEbeanConfig.java
- play-ebean/src/main/java/play/db/ebean/EbeanConfig.java
- play-ebean/src/main/java/play/db/ebean/EbeanDynamicEvolutions.java
- play-ebean/src/main/java/play/db/ebean/TransactionalAction.java
- play-ebean/src/main/java/play/db/ebean/package-info.java
- project/build.properties
- project/plugins.sbt
- sbt-play-ebean/src/main/scala/play/ebean/sbt/PlayEbean.scala
- sbt-play-ebean/src/sbt-test/sbt-ebean/enhancement/app/models/Task.java
- version.sbt
branch supporting play framework 2.5.X and Ebean 10.3.2
this pull request shall support a new plugin release, asked in issue https://github.com/playframework/play-ebean/issues/121
> New versioning branch for play framework 2.5 and Ebean 10.3.2

- README.md
> Added the 3.1.0 version to the README.

- play-ebean/src/main/java/play/db/ebean/DefaultEbeanConfig.java
This was missing after updating Ebean dependencies.
> [4.0.x]: Fix compilation problem

- README.md
- build.sbt
- docs/build.sbt
- docs/project/build.properties
- docs/project/plugins.sbt
- project/build.properties
- sbt-play-ebean/src/sbt-test/sbt-ebean/enhancement/build.sbt
- sbt-play-ebean/src/sbt-test/sbt-ebean/model-loading/build.sbt
> [4.1.x]: Update Play to 2.6.13 and other deps

- build.sbt
Relates to https://github.com/playframework/playframework/issues/8592#issuecomment-453764924
> upgrade to 2.7.0-RC9

- .travis.yml
- build.sbt
- project/plugins.sbt
May fail due to lack of sync between release and maven central repositories.
> Configure mima plugin

- docs/manual/working/javaGuide/main/sql/code/ebean.sbt
Per the play ebean docs 5.0.0 is require for play 2.7
> Per the play ebean docs 5.0.0 is required for 2.7

- README.md
Version 5.0.1 is not present in README.md
> Update readme.md acording last tag

- .travis.yml
> Remove secrets (provided via Travis UI now)

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
- .travis.yml
- build.sbt
- docs/build.sbt
- docs/project/build.properties
- docs/project/plugins.sbt
- project/Dependencies.scala
- project/build.properties
- project/plugins.sbt
- sbt-play-ebean/src/sbt-test/sbt-ebean/enhancement/build.sbt
- sbt-play-ebean/src/sbt-test/sbt-ebean/model-loading/build.sbt
I also added correct secrets to Travis, let's see if snapshots get published.
> Upgrade versions

- .gitignore
- README.md
> [5.0.x] Rename master branch to main

- project/Dependencies.scala
> [6.2.x] No need for these dependencies for the plugin

- .github/workflows/build-test.yml
> [6.2.x] Semantic Scala version selector expression in workflows

- docs/project/build.properties
- docs/project/plugins.sbt
- project/build.properties
- sbt-play-ebean/src/sbt-test/sbt-ebean/enhancement/project/plugins.sbt
- sbt-play-ebean/src/sbt-test/sbt-ebean/model-loading/project/plugins.sbt
> Revert "Workaround scala-xml dependency problem" / sbt 1.8.0-RC1 

- .github/workflows/build-test.yml
- build.sbt
- docs/build.sbt
- project/Dependencies.scala
- sbt-play-ebean/src/sbt-test/sbt-ebean/enhancement/build.sbt
- sbt-play-ebean/src/sbt-test/sbt-ebean/model-loading/build.sbt
This branch add the support for Scala 3 to Play ebean
> Add support for scala3

- play-ebean/src/main/java/play/db/ebean/DefaultEbeanConfig.java
- play-ebean/src/main/java/play/db/ebean/EBeanComponents.java
- play-ebean/src/main/java/play/db/ebean/EbeanConfig.java
- play-ebean/src/main/java/play/db/ebean/EbeanDynamicEvolutions.java
- play-ebean/src/main/java/play/db/ebean/EbeanModule.java
- play-ebean/src/main/java/play/db/ebean/EbeanParsedConfig.java
- play-ebean/src/main/java/play/db/ebean/ModelsConfigLoader.java
- play-ebean/src/main/java/play/db/ebean/Transactional.java
- play-ebean/src/main/java/play/db/ebean/TransactionalAction.java
- play-ebean/src/main/java/play/db/ebean/package-info.java
- play-ebean/src/test/java/play/db/ebean/EBeanComponentsTest.java
- play-ebean/src/test/java/play/db/ebean/EbeanParsedConfigTest.java
- project/Common.scala
- sbt-play-ebean/src/main/scala/play/ebean/sbt/PlayEbean.scala
Yet step for this repo related with https://github.com/playframework/play-meta/issues/211
PS: as another good point, this PR is a WA for https://github.com/sbt/sbt-header/issues/313
> Sync `headerEmptyLine` setting with core repo

- play-ebean/src/main/java/play/db/ebean/EbeanDynamicEvolutions.java
Preferred since Play 2.8: https://www.playframework.com/documentation/2.8.x/Migration27#Evolutions-comment-syntax
> Use SQL92 comment syntax

- build.sbt
This reverts commit add128a31855925084f945540929afca2d750224.
> Revert "Temporary disable MiMa"

- build.sbt
> Set mimaPreviousArtifacts.value to last "major" release

- build.sbt
> [7.0.x] Set mimaPreviousArtifacts.value to last "major" release

- README.md
The same as https://github.com/playframework/playframework/pull/12775
> Update Twitter -> X in README.md

- .github/scala-steward.conf
> [7.x] Pin play
